### ISSUE TITLE
len error

### ISSUE THREAD

**Issue by dairuo678** [zyj-111/GCformer#7]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/GCformer：用于准确且可扩展的长期多变量时间序列预测的有效框架/GCformer-main/GCformer-main/run_longExp.py", line 156, in <module>
    exp.train(setting)
  File "C:\Users\Administrator\Desktop\GCformer：用于准确且可扩展的长期多变量时间序列预测的有效框架\GCformer-main\GCformer-main\exp\exp_main.py", line 98, in train
    vali_data, vali_loader = self._get_data(flag='val')
  File "C:\Users\Administrator\Desktop\GCformer：用于准确且可扩展的长期多变量时间序列预测的有效框架\GCformer-main\GCformer-main\exp\exp_main.py", line 43, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "C:\Users\Administrator\Desktop\GCformer：用于准确且可扩展的长期多变量时间序列预测的有效框架\GCformer-main\GCformer-main\data_provider\data_factory.py", line 45, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0

**Comment by Yanjun-Zhao** [comment]
我clone到本地后不修改直接跑sh是没问题的。

**Comment by dairuo678** [comment]
我是用自己数据集来跑，跟ETTm1是一样的结构，但是显示__len__错误，你有遇到过类似问题吗

**Comment by Yanjun-Zhao** [comment]
检查下dataloader？

**Comment by dairuo678** [comment]
好的，感谢回复

**Comment by ooOPPPPPS** [comment]
请问下是不是不能多卡跑呀，需要自己修改decoder呀

**Comment by DaZhaoo** [comment]
数据集要下载哪个去跑?
在那里添加数据集路径?
小白求告知!

**Comment by dairuo678** [comment]
想要调用别的模型失败了，请问是源代码问题吗
